# Generated by Copilot (Claude Haiku 4.5): Hardened N|Solid app container for running Chrome DevTools MCP server.
FROM nodesource/nsolid:latest

WORKDIR /app

# Install curl for healthcheck
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*

# Copy entire project (required for npm prepare script)
COPY . .

# Install all dependencies (build requires dev dependencies for prepare/bundle)
RUN npm ci

# Build the project
RUN npm run bundle

# Create launcher scripts
COPY start.sh /usr/local/bin/start-mcp.sh
COPY wrapper.sh /usr/local/bin/wrapper.sh
RUN chmod +x /usr/local/bin/start-mcp.sh /usr/local/bin/wrapper.sh

# Expose default MCP server port (stdio-based, but can be used with network bridges)
EXPOSE 3000

# Set production environment
ENV NODE_ENV=production

ENTRYPOINT ["/usr/local/bin/start-mcp.sh"]
