#!/usr/bin/env bash
# Generated by Copilot (Claude Haiku 4.5): Starts Chrome DevTools MCP server under a hardened N|Solid runtime profile with security hardening.

set -euo pipefail

# Configuration from environment variables
ALLOW_FS_READ="${ALLOW_FS_READ:-/app}"
ALLOW_FS_WRITE="${ALLOW_FS_WRITE:-/tmp}"

echo "[mcp-server] launching nsolid with hardened flags for Chrome DevTools MCP"

# Run via wrapper script to set descriptive process name
/usr/local/bin/wrapper.sh &

# Keep container alive
tail -f /dev/null
