#!/usr/bin/env bash
# Generated by Copilot (Claude Haiku 4.5): Wrapper script that runs the Chrome DevTools MCP server as 'chrome-devtools-mcp' process

exec -a chrome-devtools-mcp /usr/local/bin/nsolid \
  --disable-proto=throw \
  --no-addons \
  --jitless \
  build/src/index.js
