/**
 * @license
 * Generated by GitHub Copilot using Claude Sonnet 4.5
 * 
 * N|Solid Process Heartbeat for Chrome DevTools MCP Server
 * This enables the Chrome DevTools MCP server to appear in the N|Solid Open UI dashboard.
 */

import {createRequire} from 'node:module';
import process from 'node:process';

const require = createRequire(import.meta.url);
const http = require('node:http');
const os = require('node:os');

export class ProcessHeartbeat {
  private clickhouseUrl: string;
  private clickhouseDb: string;
  private clickhouseUser: string;
  private clickhousePassword: string;
  private appName: string;
  private interval: number;
  private timer: NodeJS.Timeout | null = null;
  private lastCpuUsage: NodeJS.CpuUsage;
  private lastCheckTime: number;

  constructor(options: {
    clickhouseUrl?: string;
    clickhouseDb?: string;
    clickhouseUser?: string;
    clickhousePassword?: string;
    appName?: string;
    interval?: number;
  } = {}) {
    this.clickhouseUrl = options.clickhouseUrl || process.env.CLICKHOUSE_URL || 'http://clickhouse:8123';
    this.clickhouseDb = options.clickhouseDb || process.env.CLICKHOUSE_DB || 'nsolid';
    this.clickhouseUser = options.clickhouseUser || process.env.CLICKHOUSE_USER || 'nsolid';
    this.clickhousePassword = options.clickhousePassword || process.env.CLICKHOUSE_PASSWORD || 'nsolid_password';
    this.appName = options.appName || process.env.NSOLID_APP || process.env.OTEL_SERVICE_NAME || process.title;
    this.interval = options.interval || 5000; // 5 seconds
    this.lastCpuUsage = process.cpuUsage();
    this.lastCheckTime = Date.now();
  }

  /**
   * Calculate CPU percentage since last check
   */
  private getCpuPercent(): number {
    const now = Date.now();
    const currentUsage = process.cpuUsage();
    const elapsedMs = now - this.lastCheckTime;
    const elapsedUs = elapsedMs * 1000;

    const userDiff = currentUsage.user - this.lastCpuUsage.user;
    const systemDiff = currentUsage.system - this.lastCpuUsage.system;
    const totalDiff = userDiff + systemDiff;

    this.lastCpuUsage = currentUsage;
    this.lastCheckTime = now;

    // Calculate percentage (total CPU time / elapsed time) * 100
    return elapsedUs > 0 ? Math.min(100, (totalDiff / elapsedUs) * 100) : 0;
  }

  /**
   * Get current process metrics
   */
  private getMetrics() {
    const mem = process.memoryUsage();
    const cpu = this.getCpuPercent();

    return {
      timestamp: Math.floor(Date.now() / 1000), // Unix timestamp
      pid: process.pid,
      title: this.appName,
      cpu: cpu,
      memory: mem.rss,
      heap_used: mem.heapUsed,
      heap_total: mem.heapTotal,
      event_loop_delay: 0,
      uptime: process.uptime(),
      version: process.version,
      hostname: os.hostname(),
    };
  }

  /**
   * Write metrics to ClickHouse
   */
  private async writeMetrics(): Promise<boolean> {
    const metrics = this.getMetrics();

    // Format: INSERT INTO nsolid.process_metrics FORMAT JSONEachRow
    const data = JSON.stringify(metrics);
    const query = `INSERT INTO ${this.clickhouseDb}.process_metrics FORMAT JSONEachRow`;

    return new Promise((resolve) => {
      const url = new URL(this.clickhouseUrl);
      const params = new URLSearchParams({
        user: this.clickhouseUser,
        password: this.clickhousePassword,
        database: this.clickhouseDb,
        query: query,
      });

      const options = {
        hostname: url.hostname,
        port: url.port || 8123,
        path: `/?${params}`,
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(data),
        },
        timeout: 5000,
      };

      const req = http.request(options, (res: any) => {
        let responseData = '';
        res.on('data', (chunk: any) => responseData += chunk);
        res.on('end', () => {
          if (res.statusCode === 200) {
            console.log(`[heartbeat] Metrics written: ${metrics.title} (PID: ${metrics.pid})`);
            resolve(true);
          } else {
            console.error(`[heartbeat] ClickHouse error: ${res.statusCode} - ${responseData}`);
            resolve(false);
          }
        });
      });

      req.on('error', (err: Error) => {
        console.error(`[heartbeat] Request error:`, err.message);
        resolve(false);
      });

      req.on('timeout', () => {
        req.destroy();
        console.error(`[heartbeat] Request timeout`);
        resolve(false);
      });

      req.write(data);
      req.end();
    });
  }

  /**
   * Start sending periodic heartbeats
   */
  public start(): void {
    if (this.timer) {
      console.error('[heartbeat] Already started');
      return;
    }

    console.log(`[heartbeat] Starting for ${this.appName} (interval: ${this.interval}ms)`);

    // Send initial heartbeat immediately
    this.writeMetrics().catch(err => console.error('[heartbeat] Initial write failed:', err));

    // Then send periodically
    this.timer = setInterval(() => {
      this.writeMetrics().catch(err => console.error('[heartbeat] Periodic write failed:', err));
    }, this.interval);

    // Unref so it doesn't prevent process exit
    if (this.timer.unref) {
      this.timer.unref();
    }
  }

  /**
   * Stop sending heartbeats
   */
  public stop(): void {
    if (this.timer) {
      clearInterval(this.timer);
      this.timer = null;
      console.log('[heartbeat] Stopped');
    }
  }
}
