/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 * 
 * Generated by GitHub Copilot using Claude Sonnet 4.5
 * 
 * This file sets up a long-running HTTP server for the Chrome DevTools MCP.
 * The server maintains state for humanizing features and browser sessions.
 */

import './polyfill.js';

import {createServer} from 'node:http';
import process from 'node:process';
import {randomUUID} from 'node:crypto';

import {cliOptions, parseArguments} from './cli.js';
import {logger, saveLogsToFile} from './logger.js';
import {createMcpServer} from './server.js';
import {computeFlagUsage} from './telemetry/flagUtils.js';
import {StreamableHTTPServerTransport} from './third_party/index.js';
import {VERSION} from './version.js';

export const args = parseArguments(VERSION);

const logFile = args.logFile ? saveLogsToFile(args.logFile) : undefined;
// Usage statistics collection is disabled - no data exfiltration
args.usageStatistics = false;

if (process.env['CHROME_DEVTOOLS_MCP_CRASH_ON_UNCAUGHT'] !== 'true') {
  process.on('unhandledRejection', (reason, promise) => {
    logger('Unhandled promise rejection', promise, reason);
  });
}

logger(`Starting Chrome DevTools MCP Server v${VERSION}`);

const logDisclaimers = () => {
  console.error(
    `chrome-devtools-mcp exposes content of the browser instance to the MCP clients allowing them to inspect,
debug, and modify any data in the browser or DevTools.
Avoid sharing sensitive or personal information that you do not want to share with MCP clients.`,
  );

  if (!args.slim && args.performanceCrux) {
    console.error(
      `Performance tools may send trace URLs to the Google CrUX API to fetch real-user experience data. To disable, run with --no-performance-crux.`,
    );
  }

  if (!args.slim && args.usageStatistics) {
    console.error(
      `
Google collects usage statistics to improve Chrome DevTools MCP. To opt-out, run with --no-usage-statistics.
For more details, visit: https://github.com/ChromeDevTools/chrome-devtools-mcp#usage-statistics`,
    );
  }
};

const {server, clearcutLogger} = await createMcpServer(args, {
  logFile,
});

// Create a stateful HTTP transport with session management
// This allows the server to maintain state for humanizing features
const transport = new StreamableHTTPServerTransport({
  sessionIdGenerator: () => randomUUID(),
});

await server.connect(transport);

// Create HTTP server for long-running process
const PORT = process.env.PORT ? parseInt(process.env.PORT, 10) : 3000;
const httpServer = createServer((req, res) => {
  // Enable CORS for development
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  
  if (req.method === 'OPTIONS') {
    res.writeHead(200);
    res.end();
    return;
  }

  // Handle MCP requests
  transport.handleRequest(req, res).catch(error => {
    logger('Error handling request:', error);
    if (!res.headersSent) {
      res.writeHead(500, {'Content-Type': 'text/plain'});
      res.end('Internal Server Error');
    }
  });
});

httpServer.listen(PORT, () => {
  logger(`Chrome DevTools MCP Server running on http://localhost:${PORT}`);
  logger('Chrome DevTools MCP Server connected');
  console.error(`\nServer is running at: http://localhost:${PORT}`);
  console.error(`Session ID: ${transport.sessionId || 'stateless'}\n`);
  logDisclaimers();
});

void clearcutLogger?.logDailyActiveIfNeeded();
void clearcutLogger?.logServerStart(computeFlagUsage(args, cliOptions));

// Graceful shutdown
process.on('SIGINT', () => {
  logger('Received SIGINT, shutting down gracefully...');
  httpServer.close(() => {
    logger('HTTP server closed');
    process.exit(0);
  });
});

process.on('SIGTERM', () => {
  logger('Received SIGTERM, shutting down gracefully...');
  httpServer.close(() => {
    logger('HTTP server closed');
    process.exit(0);
  });
});
